### ISSUE TITLE
Some user report that db migration didn't work 

### ISSUE THREAD

**Issue by JWardee** [JWardee/wp-mail-catcher#159]
https://wordpress.org/support/topic/database-errors-78/
https://wordpress.org/support/topic/database-errors-with-last-release/

* Need to add a button to manually re-trigger the migrations
* Is there a situation where the db version in the options is updated successfully but the migration failed? Might need to wrap in a try/catch/transaction statement
* Add test to cover this possibility

**Comment by glorious1** [comment]
I've got an error that is different but may have the same root cause.  You mention something about migrating database - I seem to recall doing that and was told it was successful.
`WordPress database error Unknown column 'is_html' in 'field list' for query UPDATE `wp75_mail_catcher_logs` SET `is_html` = '1' WHERE `id` = '9652' made by wp_signon, do_action('wp_login'), WP_Hook->do_action, WP_Hook->apply_filters, wordfence::loginAction, do_action('wordfence_security_event'), WP_Hook->do_action, WP_Hook->apply_filters, wfCentral::sendAlertCallback, wfNonAdminLoginAlert->send, wordfence::alert, wp_mail, apply_filters('wp_mail_content_type'), WP_Hook->apply_filters, WpMailCatcher\Loggers\WpMail->saveIsHtml`

**Comment by JWardee** [comment]
Hey @glorious1, this should be fixed in the next patch (#161)
